### ISSUE TITLE
[Autocomplete] Multiple selection is broken, can't set the initial value

### ISSUE THREAD

**Issue by rassie** [lookfirst/mui-rff#120]
**Describe the bug**
Multilpe selection autocomplete doesn't work, fails with `value.forEach is not a function` error.

**To Reproduce**
Look at the sandbox: https://codesandbox.io/s/mui-rff-autocomplete-default-value-mmcrk

**Expected behavior**
Multiple selection autocomplete field should appear and let multiple selection happen.

**Additional comments**
Sandbox has been created by forking https://codesandbox.io/s/mui-rff-autocomplete-default-value-96u9p (from #101), upgrading `mui-rff` to 1.8.1 and adding `multiple` to the component properties.

**Comment by lookfirst** [comment]
Thank you for the report, but you have a small issue in the code. The initialValues needs to be an array in order to hold the potential multiple initial values. Hence the error for `forEach`.

![image](https://user-images.githubusercontent.com/85355/74250898-2bb54600-4ca0-11ea-8eac-dd9558f8f5ae.png)

I'm going to close this to keep the tracker clean, but by all means feel free to continue the discussion!

**Comment by rassie** [comment]
The basic problem is that a missing initial value (e.g. `Autocomplete` component without an enclosing `Form` with an `initialValues` property) leads to that error, which probably should be guarded against in some way. I'm not really sure how common or correct such a situation might be, I've only reported what we've found in colleague's code. He might have been confused by the examples (I would have been too) which do not contain any enclosing `Form` elements, so a new user might be inclined to take his first steps with standalone components only.

**Comment by lookfirst** [comment]
Fantastic feedback, thanks! Yes, the separation of components and their data is a really excellent advance in building forms, but definitely a bit confusing for us old hats.

While this is documented in the actual example app page, I just added some documentation to the readme in order to hopefully prevent further confusion, let me know what you think?

https://github.com/lookfirst/mui-rff/blob/master/README.md#autocomplete---mui-docs

I am avoiding adding too much guard code to this project as it penalizes download sizes for all the people who get it right. Yes, I know just a few bytes, but might as well try to be conservative. So hopefully the added documentation works. If not and I get more reports, I'll add the guard code too.

**Comment by rassie** [comment]
Perfect, thank you very much! This should be enough to avoid confusion which is basically all I'm after.

**Comment by lookfirst** [comment]
Sweet! Glad I could help. Have a great day. =) If you come up with other ideas for improvement, please let me know.
