### ISSUE TITLE
[bug] Field components don't accept default value for margin

### ISSUE THREAD

**Issue by depiction** [lookfirst/mui-rff#144]
When creating a Material UI theme, you can define default props for components. For example, I changed the default value for the margin and variant props for text fields. 

    const theme = createMuiTheme({
        props: {
            MuiTextField: {
                margin: "dense",
                variant: "outlined"
            }
        }
    });

MUI-RFF recognizes the variant prop default, but not the margin prop because in mui-rff.esm.js, the margin is hard-coded to "normal". I can still set the margin to dense, but I have to set it on every TextField component.

**Comment by lookfirst** [comment]
Yes, you will need to override it. A simple one line wrapper in your codebase is all you need.

```js
export function DenseTextField(props) {
   return <TextField margin="dense" {...props} />;
}
```

I do see your point here though and is something I hadn't considered before. This messes up the themeability for certain and is a very strong reason to not override that default. 

I will fix this (remove that default), but it'll have to go out in a 2.0 version since it will break people who rely on the existing default.

**Comment by lookfirst** [comment]
Yea! Just fixed this... thank you!
