### ISSUE TITLE
Why aren't you using the meta object to detect errors?

### ISSUE THREAD

**Issue by AndyOGo** [lookfirst/mui-rff#158]
**react-final-form** handles all the state for you and gives you the final errors [`meta.error`](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metaerror), [`meta.submitError`](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metasubmiterror), [`meta.submitFailed`](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metasubmitfailed), [`meta.modified`](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metamodified), [`meta.touched`](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metatouched), ... already.

I think using custom hooks is not necessary, like:
https://github.com/lookfirst/mui-rff/blob/7bc2574bb271e851bdffc0dcda1b6cae95ed8469/src/TextField.tsx#L42-L49

**Comment by lookfirst** [comment]
@AndyOGo

Thanks for the issue.

Yes, you are correct for `TextField` that I should be doing it (like I am with the Date* components). I've been sick for the last week (not corona) and honestly just missed it in my haze during a bunch of refactoring. I'll fix that one for sure.

That said, for the other ones like, `Select`, `Checkboxes`, `Radios`, where the error state need to be handled outside of the `Field`, what would you suggest?

I'm also not sure what you mean by the statement... 'final errors'.

**Comment by lookfirst** [comment]
Interesting, changing this is making my 'requires a default value' test to fail. It could be a flaky test or it could be a bug or weird thing in RFF.

**Comment by lookfirst** [comment]
Hi @AndyOGo ... Ok, I've tried several different ways of doing this and I can't seem to get it to pass that one test. If you can, let me know, otherwise I'm just going to leave it as is since that is working.

**Comment by AndyOGo** [comment]
@lookfirst Thank you for you quick answers.

You are doing a great job here.

> I've been sick for the last week (not corona)

Get well soon.
Re coronavirus. Dr. Berg ist giving a great explanation and comparison to other issues:
https://www.youtube.com/watch?v=lAtAd6_Wh9Y

> That said, for the other ones like, Select, Checkboxes, Radios, where the error state need to be handled outside of the Field, what would you suggest?

Hmh, if I understood you correctly, I would handle it with validators and submission erros.
- [`FieldProps.validate`](https://final-form.org/docs/react-final-form/types/FieldProps#validate)
- [`FormProps.validate`](https://final-form.org/docs/react-final-form/types/FormProps#validate)
- [`FormProps.onSubmit`](https://final-form.org/docs/react-final-form/types/FormProps#onsubmit)

> I'm also not sure what you mean by the statement... 'final errors'.

Maybe I put my thoughts into weird wording... I meant that final-form is handling all form related state, including field and submission errors

> Interesting, changing this is making my 'requires a default value' test to fail. It could be a flaky test or it could be a bug or weird thing in RFF.

Interesting, I cant tell , I have so far used RFF only with a custom UI and components and not issues at all testing them with `jest` and `enzyme`.
I would need some time to check, I don't promise it now.

**Comment by lookfirst** [comment]
@AndyOGo Thanks for the concern. I have the runny nose congestion, my lungs are fine and no diarrhea... all common issues with the virus. But, I am staying with some friends in an isolated house on beautiful property, who have a 2.5 year old and they are little germ magnets. He has same symptoms. 99.999% sure I got what he had. I'm on the tail end of it now. =)

With regards to the components I mentioned. Please take a closer look at the code. The `<Field>` is within an outer container like `<FormControl>`, which takes an `error` property... ie: `<FormControl error={errorString}>`. So you have to be able to pass that error state 'up' the chain, but that is fundamentally the wrong way to use React.

[Originally](https://github.com/lookfirst/mui-rff/commit/207bad62a3edfb8cbfdfb1dba38420041939effb#diff-02fef3c3fd78df7217b9633451611510L103) I hacked a `useState` within the `<Field>` and referenced the value within the `<FomControl>`. But this was no good with latest React which now [shows a warning in the console](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render) about doing this. My hack was closed down.

So, I had to think of another way to move the state 'up'... it took me a few days of pondering, but I realized I could do it with hooks which are receiving their own state from a higher level.

Anyway, if you can figure out how to get the test to pass, then all good. I spent a couple hours trying to make it work, but I have a feeling there is a bug in FF that is preventing a render from happening, which is making the test not pass.

Otherwise, I think things are fine the way they are as it is tested and working right now. There is nothing wrong with using the hook. In fact, I kind of prefer hooks overall as a design choice anyway. At the end of the day, there is no functional cost here.

I'm going to close this issue for now but please don't take it to mean the discussion is over. Feel free to comment further. I will eagerly await you opening a PR, when you have time. =)
