### ISSUE TITLE
Bundle size is huge

### ISSUE THREAD

**Issue by alexvandervegt** [lookfirst/mui-rff#233]
Did you ever looked at the bundle size?

Why is it importing all material-ui components again? You can reference them from the original material-ui package?

<img width="1260" alt="Screenshot 2020-05-26 at 11 26 18" src="https://user-images.githubusercontent.com/3672692/82884579-31c7ed80-9f44-11ea-87c2-61267f308b57.png">

**Comment by lookfirst** [comment]
I'm not sure that tool is accurate, are you?

**Comment by alexvandervegt** [comment]
It is accurate. Are you including material-ui inside mui-rff?

**Comment by lookfirst** [comment]
Nope. You have the source code... take a look.

**Comment by alexjsdev** [comment]
@alexvandervegt this lib has no direct dependencies as you can see in package.json... they are all peers, and of course it does import material ui components (by name), since that's the whole point of the lib, to wrap material-ui components in react final form fields. As @lookfirst pointed out, you can see in the source, mui-rff is never imported wholesale.

If you're saying that you're only using one of the components and it's importing the entire lib, is it possible that is due to a misconfiguration of [webpack treeshaking](https://webpack.js.org/guides/tree-shaking/) on your end, or it's integration with material-ui itself? https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking 

Let me know what you end up doing. I'm curious.

**Comment by lookfirst** [comment]
I'm going to close this as I don't think it is a real issue when treeshaking is configured correctly.
