### ISSUE TITLE
DatePicker - pickerProviderWrapper is overriding the parent Provider

### ISSUE THREAD

**Issue by TarikHuber** [lookfirst/mui-rff#634]
Sorry for posting a bug report for MUI V 5. But the issue can be resolved quite easily.

The `pickerProviderWrapper` in the `DatePicker` is overriding any Provider above it and by that, the language always stays `en`. The only way to change it is to set it for each `DatePicker` itself. In smaller projects that is not a big deal but in larger ones we need to detect the used language and get the appropriate fns language for it and that for each date field.

I'm not sure why there is `pickerProviderWrapper` inside of `DatePicker`.  The `LocalizationProvider` is required by MUI anyway, Is it possible that we just remove that one? If it's OK I can send a PR for this.

**Comment by lookfirst** [comment]
Sure, send a pr. =) Please include a test too.

**Comment by aFarkas** [comment]
Yes this makes it simple to create demos but this makes all pickers unusable in any project. It actually raises the question wether this project is used in the real world.

**Comment by lookfirst** [comment]
@aFarkas Yea, I was hoping @TarikHuber would have sent a PR and unfortunately, it hasn't come up again since you just commented. Thanks for that.

Just as a side note, your comment could be taken as kind of rude by a native english speaker. This is coming from someone who has a history themself of making comments that could be considered rude and is trying to improve. 

To answer your comment, I'm pretty sure the project is being used, but the project has a lot of moving parts, so it is quite possible that this one gear isn't being used.

So... moving forward, let's fix this!

**Comment by lookfirst** [comment]
Turns out it was pretty easy to fix this. Released as 5.2.0. Enjoy.

**Comment by aFarkas** [comment]
Thank you @lookfirst.

**Comment by TarikHuber** [comment]
Thx @lookfirst. Sorry I did not send a PR. Quite occupied with other stuff.
