### ISSUE TITLE
Select multiple not supported

### ISSUE THREAD

**Issue by zacheryph** [lookfirst/mui-rff#69]
**Is your feature request related to a problem? Please describe.**
The `multiple` option for `Select` does not appear to be supported.

**Describe the solution you'd like**
`<Select multiple .../>` to be supported

**Describe alternatives you've considered**
_N/A_

**Additional context**
_N/A_

**Comment by lookfirst** [comment]
Ha! Good one. I haven't had that usecase yet. Did you want to submit a PR or I'm happy to fix it as well. =)

**Comment by lookfirst** [comment]
Fixed and released. =)

**Comment by zacheryph** [comment]
Haha. Thanks. I've been out for holiday, good to see the update so fast 😄

**Comment by lookfirst** [comment]
No problem! Let me know if you find anything else! =)

**Comment by AlessandroAnnini** [comment]
I'm sorry, can you point me to an example about this? I'm having hard times to accomplish this..
thanks @zacheryph

**Comment by lookfirst** [comment]
@AlessandroAnnini We have a test for multiple.... is there something specific you're looking for?

https://github.com/lookfirst/mui-rff/blob/master/test/Select.test.tsx#L137https://github.com/lookfirst/mui-rff/blob/master/test/Select.test.tsx#L137

**Comment by AlessandroAnnini** [comment]
oh gosh, I'm sorry, I didn't see it! but is there a way I can omit the initialValues for the select?
Without it I got this error:
`Material-UI: the 'value' prop must be an array when using the 'Select' component with 'multiple'.`

take a look at line 12

[![Edit priceless-snowflake-29git](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-snowflake-29git?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark)

I need this because I am building something that generate the form automatically and I have not a predefined structure to use for `initialValues`

**Comment by lookfirst** [comment]
The error that you are seeing [is coming from within MUI](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Select/SelectInput.js#L220). In other words, out of my control. Even `initialValues` is defined outside of the flow of MUI-RFF.

The reality is that even if the form is generated automatically, you still need to define the `initialValues` for it. If you want to post your generation code, I might be able to suggest how you can refactor things so that it works for you.

You may also want to look at the [MUI-RFF example code](https://github.com/lookfirst/mui-rff/blob/master/example/index.tsx) which shows how the components can be declared dynamically and then rendered with the appropriate data. Just imagine that the [formFields](https://github.com/lookfirst/mui-rff/blob/master/example/index.tsx#L263) variable data is built on the fly.

The splitting of data from the actual components is a good thing. It is a little odd to get used to at first, but long term I've found that this is a much better model.

**Comment by lookfirst** [comment]
@AlessandroAnnini I also just updated the example to use `Select multiple` to 'prove' it works. =)

**Comment by AlessandroAnnini** [comment]
Hi @lookfirst , i solved my problems solving some recursion issues and I have to say that it's really better to work with fieldarray!

just one thing: I could be wrong but doesn't have [mui `value` attribute](https://github.com/mui-org/material-ui/blob/c1c66903b8cc3941d0e110f13f49122effdc0e47/packages/material-ui/src/Select/Select.js#L217)? can we implement it in mui-rff too?

**Comment by lookfirst** [comment]
The `value` property is managed by React Final Form with the `initialValues`.

**Comment by AlessandroAnnini** [comment]
I understand but I should be able to use `displayEmpty` property but it seems not to be working.. should I pass this property in a particular way?

**Comment by lookfirst** [comment]
@AlessandroAnnini Thanks. You've definitely found something. I've moved this over to a new issue and I am working on a fix/release for it.
